### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by johnwc** [mayank1513/tag-input#15]
Need a property, preferably a function type, that can be called to validate the input before accepting the input as a tag.

**Comment by mayank1513** [comment]
You can pass `options` prop to restrict tags to a specific list.

**Comment by johnwc** [comment]
I don't have a list or the list is much to large, I just know the format of the data that is correct. Example, only want to accept 5 digit zip codes. Need a way to validate the text is valid 5 digits only.

**Comment by mayank1513** [comment]
Working on it, meanwhile, options can be a state created with `ref` and can be updated based on API response. Working on a better version though!

Thanks for your feedback!

**Comment by mayank1513** [comment]
Would you like to review https://github.com/mayank1513/tag-input/pull/17/files#diff-b61ef41311a331b339efc699633a6bda8299745470419362a461adeee03303dc and give your feedback?

Basically, added a prop called validator. This can be an array of string or a RegExp or a function returning boolean or a string array.

**Comment by johnwc** [comment]
It looks good, but are you expecting the validator to also be the autocomplete? I think that will be confusing to others that attempt to use the component. "I have to use the property called validator in order to implement API autocomplete??"

**Comment by mayank1513** [comment]
Hmmm! I also had the same doubt. That's why I didn't merge the PR. But, I really wanted to combine auto-complete and validator, because you don't want to make 2 API calls, one for autofill options and then the other for validation.

What do you think?

**Comment by johnwc** [comment]
Validation should never need to respond with options. Autocomplete would be the only functionality that is used for returning a list of dynamic options based on user input. It would be confusing otherwise.

**Comment by mayank1513** [comment]
I have updated the PR. Provided `autocompleteItems` which can be an array of strings or function returning array of strings.  And updated validator accordingly
